server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: empresa-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/cadastroempresas,/api/auth/**,/api/empresas/**,/api/admin/**
        - id: golpe-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cadastrogolpes/**,/api/golpes/**,/api/empresa/**